module load OpenMPI/2.1.3
module load Anaconda3/2019.07
source /polusfs/modules/anaconda/anaconda-3/etc/profile.d/conda.sh
conda activate
#BSUB -n 80 -q normal
#BSUB -W 03:00
#BSUB  -o result.out
#BSUB  -e result.err

mpiexec -n 1 python main.py
mpiexec -n 2 python main.py
mpiexec -n 4 python main.py
mpiexec -n 8 python main.py
mpiexec -n 16 python main.py
mpiexec -n 32 python main.py
mpiexec -n 64 python main.py

